
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017" # expose MongoDB to host
    volumes:
      - mongo_data:/data/db # persistent storage
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      # optional: seed/init scripts

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379" # expose Redis to host

volumes:
  mongo_data:
